# ServiceAccount for External Secrets with Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: external-secrets-sa@fahman.iam.gserviceaccount.com
---
# ClusterSecretStore - cluster-wide secret store for GCP Secret Manager
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: fahman
      auth:
        workloadIdentity:
          clusterLocation: europe-west3
          clusterName: fahman-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
